# Generated by Django 4.0.4 on 2022-05-14 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vs_currency', models.CharField(max_length=50)),
                ('price', models.BigIntegerField()),
                ('price_updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='price_tracker.coins')),
            ],
            options={
                'unique_together': {('coin_id', 'vs_currency', 'price', 'price_updated_at')},
            },
        ),
    ]
