# Generated by Django 4.0.4 on 2022-05-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0002_coinprices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coins',
            options={'verbose_name_plural': 'crypto'},
        ),
    ]
