# Generated by Django 4.0.4 on 2022-05-14 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0003_alter_coins_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinprices',
            options={'verbose_name_plural': 'crypto Prices'},
        ),
    ]
